[package]
name = "nox-observer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { version = "1.5.7", features = ["serde"] }
anyhow = "1.0.102"
axum = "0.8.8"
axum-prometheus = "0.10.0"
chrono = { version = "0.4.44", features = ["serde"] }
config = "0.15.23"
config-secret = "0.1.0"
graphql_client = { version = "0.16.0", features = ["reqwest"] }
metrics-exporter-prometheus = "0.18.1"
reqwest = { version = "0.12.28", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "postgres", "chrono"] }
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["trace", "cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
validator = { version = "0.20.0", features = ["derive"] }

[dev-dependencies]
temp-env = "0.3.6"
