use std::time::Duration;

use anyhow::{Context, Result, anyhow, bail};
use chrono::{DateTime, Utc};
use graphql_client::{GraphQLQuery, reqwest::post_graphql};
use tokio::time::{MissedTickBehavior, interval};
use tracing::{error, info, warn};

use crate::db::{Db, NewHandle};

// =====================================================================
// GraphQL types (generated by the derive macro)
// =====================================================================
type Bytes = String;
type BigInt = String;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "generated/subgraph/schema.json",
    query_path = "src/subgraph/queries.graphql",
    response_derives = "Debug, Clone"
)]
pub struct HandlesQuery;

// =====================================================================
// SubgraphClient — thin async wrapper around reqwest + graphql_client
// =====================================================================

pub struct SubgraphClient {
    http: reqwest::Client,
    url: String,
}

impl SubgraphClient {
    pub fn new(url: String) -> Result<Self> {
        let http = reqwest::Client::builder()
            .timeout(Duration::from_secs(30))
            .build()?;
        Ok(Self { http, url })
    }

    pub async fn fetch_handles(
        &self,
        last_block: BigInt,
        first: i64,
    ) -> Result<handles_query::ResponseData> {
        let variables = handles_query::Variables { first, last_block };
        let response = post_graphql::<HandlesQuery, _>(&self.http, &self.url, variables).await?;

        if let Some(errors) = response.errors
            && !errors.is_empty()
        {
            bail!("subgraph returned errors: {errors:?}");
        }

        response
            .data
            .ok_or_else(|| anyhow!("subgraph returned no data for HandlesQuery"))
    }
}

// =====================================================================
// Poller — periodic loop that fetches handles and persists them via Db
// =====================================================================

pub struct Poller {
    subgraph: SubgraphClient,
    db: Db,
    chain_id: i32,
    poll_interval: Duration,
    batch_size: i64,
    last_block: i64,
}

impl Poller {
    pub fn new(
        subgraph: SubgraphClient,
        db: Db,
        chain_id: i32,
        poll_interval: Duration,
        batch_size: i64,
    ) -> Self {
        Self {
            subgraph,
            db,
            chain_id,
            poll_interval,
            batch_size,
            last_block: 0,
        }
    }

    pub async fn run(mut self) -> Result<()> {
        let mut ticker = interval(self.poll_interval);
        ticker.set_missed_tick_behavior(MissedTickBehavior::Delay);

        info!("poller started; poll_interval={:?}", self.poll_interval);

        loop {
            ticker.tick().await;
            match self.poll_once().await {
                Ok(n) if n > 0 => info!("polled {n} handles (last_block={})", self.last_block),
                Ok(_) => {}
                Err(e) => error!("poll iteration failed: {e:#}"),
            }
        }
    }

    async fn poll_once(&mut self) -> Result<usize> {
        let data = self
            .subgraph
            .fetch_handles(self.last_block.to_string(), self.batch_size)
            .await?;

        if data.handles.is_empty() {
            return Ok(0);
        }

        let mut processed = 0;
        let mut max_block = self.last_block;

        for h in &data.handles {
            // Skip handles missing required block metadata — block_number/timestamp/tx_hash
            // are NOT NULL in our schema but nullable in the subgraph entity.
            let (Some(bn_str), Some(bt_str), Some(tx)) = (
                h.block_number.as_ref(),
                h.block_timestamp.as_ref(),
                h.transaction_hash.as_ref(),
            ) else {
                warn!("skipping handle {} with missing block metadata", h.id);
                continue;
            };

            let block_number = parse_block_number(bn_str)?;
            let block_timestamp = parse_timestamp(bt_str)?;

            let new = NewHandle {
                handle_id: h.id.clone(),
                chain_id: self.chain_id,
                operator: h.operator.clone(),
                caller: None, // filled later by nats_consumer
                tx_hash: tx.clone(),
                block_timestamp,
                block_number,
                resolved_at: None,
                processed_by_subgraph: true,
                processed_by_s3: false,
                processed_by_nats: false,
            };

            self.db.upsert_handle(&new).await?;

            // Best-effort parent linking: the subgraph may reference parents that
            // we never see directly (skeleton handles with NULL block metadata,
            // excluded from our `blockNumber_gt` filter). Drop those links rather
            // than failing the whole batch on a FK violation.
            for p in &h.parent_handles {
                if let Err(e) = self.db.upsert_handle_parent(&h.id, &p.id).await {
                    warn!("dropping parent link {} -> {}: {e:#}", h.id, p.id);
                }
            }

            if block_number > max_block {
                max_block = block_number;
            }
            processed += 1;
        }

        self.last_block = max_block;
        Ok(processed)
    }
}

// ============================================================================
// Mapping helpers
// ============================================================================

fn parse_block_number(s: &str) -> Result<i64> {
    s.parse::<i64>().context("invalid block_number")
}

fn parse_timestamp(s: &str) -> Result<DateTime<Utc>> {
    let secs: i64 = s.parse().context("invalid block_timestamp")?;
    DateTime::from_timestamp(secs, 0).ok_or_else(|| anyhow!("out-of-range block_timestamp: {secs}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_builds_client_with_timeout() {
        let client =
            SubgraphClient::new("https://example.com".to_string()).expect("should build client");
        assert_eq!(client.url, "https://example.com");
    }

    #[test]
    fn parse_block_number_ok() {
        assert_eq!(parse_block_number("12345").unwrap(), 12345);
    }

    #[test]
    fn parse_block_number_invalid() {
        assert!(parse_block_number("not a number").is_err());
    }

    #[test]
    fn parse_timestamp_ok() {
        let dt = parse_timestamp("1700000000").unwrap();
        assert_eq!(dt.timestamp(), 1700000000);
    }
}
